# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NUMI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NUMI
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Push', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'

  

  platform :ios, '9.0'
  pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'NUMITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NUMI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NUMI-tvOS

  target 'NUMI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
